# # # # # # # # # # # # #
#    Neha Kay's Blog    #
# # # # # # # # # # # # #

# Basic
name:               "Neha Kay's Blog"

author:
  facebook:         your-id
  youtubeUser:      your-id
  youtubeChannel:   your-id
  twitter:          your-id
  github:           your-id
  stackoverflow:    your-id
  quora:            your-id
  linkedin:         your-id
  pinterest:        your-id
  googlePlus:       your-id
  instagram:        your-id
  reddit:           your-id
  medium:           your-id
  tumblr:           your-id
  email:            neha@nehakay.com

copyright:
  year:             2017
  name:             Neha Kay

# Google-analytics
google-analytics:
  id:               "UA-102145407-1"

# Disqus
disqus:
  id:               "neha-kay"

# URL
#url:                "nehakay.com" # the base hostname & protocol for your site
#url:                "http://localhost:4000" # use this url when you develop
baseurl:            "" # the subpath of your site, e.g. /blog


# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:           Asia/Seoul
permalink:          /:year-:month-:day/:title/

# Pagination
paginate:           200
paginate_path:      /page:num/

# Markdown
markdown:           kramdown
kramdown:
  input:            GFM

# Navigation
nav:
  - name:           "About"
    url:            "/about"
  - name:           "Archive"
    url:            "/archive"
  - name:           "Daily Musings"
    url:            "https://neha-kay.github.io/2017-07-01/daily-musings/"
  - name:           "Guides"
    url:            "https://neha-kay.github.io/2017-07-05/guides/"
  - name:           "Photos"
    url:            "https://www.flickr.com/photos/150567501@N07/"
    
# Sass
sass:
  sass_dir:         _sass
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# jekyll-seo-tag, see: http://www.rubydoc.info/gems/jekyll-seo-tag/1.2.0
gems:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-admin

exclude:            [vendor]
